
POST http://127.0.0.1:8888/user/register
Content-Type: application/json

{
  "username": "wadwings",
  "password": "wadwings",
  "email": "wingswad@gmail.com"
}
###
POST http://localhost:8888/user/login?type=email
Content-Type: application/json

{
  "email": "wingswad@gmail.com",
  "password": "wadwings"
}
###
POST http://localhost:8888/user/login?type=username
Content-Type: application/json

{
  "username": "wadwings",
  "password": "wadwings"
}
###
POST http://tx.dedsec.site:8888/user/register
Content-Type: application/json

{
"username": "wadwings",
"password": "wadwings",
"email": "wingswad@gmail.com"
}

###
POST http://tx.dedsec.site:8888/user/login
Content-Type: application/json

{
  "username": "wadwings",
  "password": "wadwings"
}