
POST http://127.0.0.1:8888/user/register
Content-Type: application/json

{
  "username": "wadwings",
  "password": "wadwings",
  "email": "wingswad@gmail.com"
}
###
POST http://localhost:8888/user/login
Content-Type: application/json

{
  "username": "wadwings",
  "password": "wadwings"
}